In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Load dataset
df = pd.read_csv("diabetes_prediction_dataset.csv")

# Explore dataset
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [4]:
# check missing values
df.isna().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [5]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [10]:
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [11]:
# Preprocess data
# Convert categorical variables into numerical variables
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['gender'] = label_encoder.fit_transform(df['gender'])
df['smoking_history'] = label_encoder.fit_transform(df['smoking_history'])
df['HbA1c_level'] = label_encoder.fit_transform(df['HbA1c_level'])

In [12]:
# check Data Frame
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,4,25.19,11,140,0
1,0,54.0,0,0,0,27.32,11,80,0
2,1,28.0,0,0,4,27.32,5,158,0
3,0,36.0,0,0,1,23.45,4,155,0
4,1,76.0,1,1,1,20.14,3,155,0

In [31]:
# check nbr of diabetes positive
df.diabetes[df["diabetes"] == 1].count()

8500

In [30]:
# check nbr of diabetes negative
df.diabetes[df["diabetes"] == 0].count()

91500

In [33]:
df[df["diabetes"] == 1]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
6,0,44.0,0,0,4,19.31,10,200,1
26,1,67.0,0,1,5,27.32,10,200,1
38,1,50.0,1,0,1,27.32,5,260,1
40,1,73.0,0,0,3,25.91,17,160,1
53,0,53.0,0,0,3,27.32,13,159,1
...,...,...,...,...,...,...,...,...,...
99935,0,65.0,1,1,4,33.55,15,140,1
99938,1,55.0,0,1,3,30.42,9,300,1
99957,0,61.0,0,0,0,34.45,10,280,1
99962,0,58.0,1,0,4,38.31,13,200,1
99979,0,61.0,0,0,1,30.11,9,240,1

In [34]:
# Separate features and target variable
X = df.drop(['diabetes'], axis=1).values
y = df['diabetes'].values

# Split data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [35]:
# Import different machine learning algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [36]:
# Create a dictionary of classifiers
classifier = {'Logistic Regression': LogisticRegression(),
              'Support Vector Machine': SVC(),
              'Decision Tree Classifier': DecisionTreeClassifier(),
              'Random Forest Classifier': RandomForestClassifier()}

# Train and evaluate different classifiers
for name, clf in classifier.items():
    clf.fit(X_train, y_train)
    print(name)
    print("Accuracy on training set: {:.2f}".format(clf.score(X_train, y_train)))
    print("Accuracy on testing set: {:.2f}".format(clf.score(X_test, y_test)))
    print()

C:\Users\alaa\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
Accuracy on training set: 0.95
Accuracy on testing set: 0.95

Support Vector Machine
Accuracy on training set: 0.96
Accuracy on testing set: 0.96

Decision Tree Classifier
Accuracy on training set: 1.00
Accuracy on testing set: 0.95

Random Forest Classifier
Accuracy on training set: 1.00
Accuracy on testing set: 0.97

In [37]:

# Evaluate model using k-fold cross validation
from sklearn.model_selection import cross_val_score

for name, clf in classifier.items():
    scores = cross_val_score(clf, X, y, cv=5) # 5-fold cross validation
    print(name)
    print("Scores: {}".format(scores))
    print("Mean score: {:.2f}".format(scores.mean()))
    print("Standard Deviation: {:.2f}".format(scores.std()))
    print()

C:\Users\alaa\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\alaa\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\alaa\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\alaa\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\alaa\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
Scores: [0.95815 0.95765 0.9511  0.95835 0.95705]
Mean score: 0.96
Standard Deviation: 0.00

Support Vector Machine
Scores: [0.9634  0.9637  0.96155 0.9632  0.9625 ]
Mean score: 0.96
Standard Deviation: 0.00

Decision Tree Classifier
Scores: [0.95355 0.9511  0.95015 0.95135 0.95135]
Mean score: 0.95
Standard Deviation: 0.00

Random Forest Classifier
Scores: [0.97035 0.9703  0.968   0.97025 0.9703 ]
Mean score: 0.97
Standard Deviation: 0.00

In [38]:

# Model selected: Random Forest Classifier
# Train final model
final_model = RandomForestClassifier()
final_model.fit(X, y)

RandomForestClassifier()

In [63]:
# Make predictions on new data
patient1 = np.array([1, 50, 0, 1, 2, 170, 7, 270]).reshape(1, -1) ## diabetes = 1
patient2 = np.array([0, 35, 1, 0, 1, 25, 1, 140]).reshape(1, -1) ## no_diabetes = 0

In [64]:
y1 = final_model.predict(patient1) 
print(y1)

[1]

In [65]:
y2 = final_model.predict(patient2)
print(y2)

[0]